name: releng
on:
  push:
    branches:
      - master

jobs:
  archlinux:
    runs-on: ubuntu-latest
    container: archlinux:latest

    strategy:
      matrix:
        include:
          - lua-version: 5.4
            pkg: lua
            bin: lua
          - lua-version: 5.3
            pkg: lua53
            bin: lua5.3
          - lua-version: 5.2
            pkg: lua52
            bin: lua5.2
          - lua-version: 5.1
            pkg: lua51
            bin: lua5.1

    name: lua ${{ matrix.lua-version }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare
        run: |
          pacman -Sy --noconfirm base-devel cmake openssl ${{ matrix.pkg }}

      - name: build
        run: |
          mkdir build; cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          make
          make install

      - name: test
        run: ${{ matrix.bin }} test.lua
