name: releng
on:
  push:
    branches:
      - master

jobs:
  qa:
    runs-on: ubuntu-latest
    container: archlinux:latest

    strategy:
      matrix:
        include:
          - lua-version: 5.4
            pkg: lua
            bin: lua
            ver: LUA54
          - lua-version: 5.3
            pkg: lua53
            bin: lua5.3
            ver: LUA53

    name: lua ${{ matrix.lua-version }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare
        run: |
          pacman -Sy --noconfirm base-devel cmake openssl ${{ matrix.pkg }}

      - name: build
        run: |
          mkdir build; cd build
          cmake .. -D${{ matrix.ver }}=1 -DCMAKE_INSTALL_PREFIX=/usr
          make
          make install

      - name: test
        run: ${{ matrix.bin }} test.lua

  pkg:
    runs-on: ubuntu-latest
    container: archlinux:latest
    needs: qa

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare
        run: |
          pacman -Sy --noconfirm base-devel git cmake openssl lua lua53
          useradd -m -d /__w/srp/srp -s /bin/bash build
          chown -R build /__w/srp/srp

      - name: package
        run: |
          cd dist
          su build -c makepkg
